---
- name: This play installs needed tools to provision infrastructure VMs
  hosts: localhost
  become: true
  vars_files:
    - vars/libvirt.yml
  vars:
    gopath: "~/go"
  tasks:

    - name: Download and provision Terraform
      unarchive: 
        src: https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
        dest: /usr/bin/
        mode: 755
        remote_src: yes

    - name: Install qemu, libvirt, git
      yum:
        name: "{{ virtualization_packages }}"
        state: latest

    - name: Virtualization services are enabled
      service:
        name: libvirtd
        state: started
        enabled: true

    - git:
        repo: https://github.com/dmacvicar/terraform-provider-libvirt.git
        dest: ~/libvirt-provider

    - name: Run 'install' target as root
      make:
        chdir: ~/libvirt-provider
        target: install
      become: yes

    - name: Ensures terraform plugins directory exists
      file:
        path: ~/.terraform/plugins
        state: directory

    - name: Copy libvirt provider to plugins directory
      copy:
        src: "{{ gopath }}/bin/terraform-provider-libvirt"
        dest: ~/.terraform.d/plugins/

    - name: Ensure pool path exists
      file:
        path: "{{ libvirt.storage.pool_path }}"
        state: directory

    - name: Define libvirt network
      virt_net:
        command: define
        name: "{{ libvirt.network.network_name }}"
        xml: '{{ lookup("template", "templates/libvirt_network.xml.j2") }}'
        autostart: true
        state: active

    - name: Define libvirt pool
      virt_pool:
        command: define
        name: vms
        xml: '{{ lookup("template", "templates/libvirt_pool.xml.j2") }}'
        autostart: true
        state: active
