virtualization_packages:
  centos7:
    - git
    - unzip 
    - gcc
    - make
    - python-lxml
    - python-netaddr
    - python-libvirt
    - libvirt-devel
    - libvirt
    - qemu-kvm
    - virt-install
    - virt-manager
  centos8:
    - unzip
    - git
    - gcc
    - make
    - python3-lxml
    - python3-netaddr
    - python3-libvirt
    - libvirt-devel
    - libvirt
    - qemu-kvm
    - virt-install
    - virt-manager
  fedora:
    - unzip
    - git
    - gcc
    - make
    - python3-lxml
    - python3-netaddr
    - python3-libvirt
    - libvirt-devel
    - libvirt
    - qemu-kvm
    - virt-install
    - virt-manager
